server:
  port: 9001
spring:
  application:
    name: mars-stock-service

  cloud:
    nacos:
      discovery:
        # 指定nacos server地址
        server-addr: localhost:8848
        # 指定集群名称
        cluster-name: NJ
        metadata:
          version: v3

